name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Mã nguồn Checkout
      uses: actions/checkout@v4

    - name: Cấu hình Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cài đặt thư viện (Dependencies)
      run: npm install

    - name: Chạy Unit Test (Jest)
      run: npm test
